version: 2
jobs:
  build:
    working_directory: ~/workdir

    docker:
      - image: circleci/android:api-28-alpha

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "rules4android/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "rules4android/build.gradle" }}
      - run:
          name: Build
          command: ./gradlew clean assemble lint test
      - store_artifacts:
          path: exampleapp/build/reports/
          destination: example-app-reports
      - store_artifacts:
          path: rules4android/build/reports/
          destination: rules4android-reports
      - store_artifacts:
          path: rules4android/build/outputs/aar/
          destination: rules4android-aar